### ISSUE TITLE
abstraction for setting up compiler stages

### ISSUE THREAD

**Issue by problame** [comprakt/comprakt#112]
* We duplicate the setup + glue code for separate compiler stages in a lot of places:
  * `compiler/cli/src/main.rs` => `setup_io!()` + `cmd_.*`
    * AsciiFile from mmaped file, file described as PathBuf
  * parser + semantics tests generated by mjtest-rs
    * AsciiFile from &Vec<u8> (test case file read to memory)

* All stages that use the lexer need to make it the *unforgiving lexer*, follow the copy pasta trace throughout the code base by searching for that string

* @reiner-dolp already started something in branch https://github.com/comprakt/comprakt/tree/reiner/compiler-driver

**Comment by joshuabach** [comment]
I think this is only possible by moving ownership of the src buffer into Asciifile. I see two ways of doing that:
 1) Instead of `mapping: &'src [u8]`, `AsciiFile` has to hold a `mapping: Mmap` (or some form of *owning* abstraction over that, to handle the empty file case.
 2) `AsciiFile` has to hold a `mapping: M`, where `M: Deref<Target=[u8]>` (`Mmap` or a simple abstraction over it satisfies this).

Variant 2 is more generic, but comes at the disadvantage of being more generic. Everything that holds a context will need to have a `M: Deref<Target=[u8]>` generic type parameter. Variant 1 is simpler, but makes the compiler only work with mmap.

**Comment by problame** [comment]
One of the *must* requirements is that tests with input from String can be written easily.

**Comment by problame** [comment]
Sort of done as of 58f35a7eacd92a207e5504d53267a39d038b594a
